### ISSUE TITLE
Connectivity blueprint atlases available for individual HCP subjects?

### ISSUE THREAD

**Issue by bwinsto2** [SPMIC-UoN/XTRACT_atlases#1]
Hello--thank you for this excellent work. Apologies if I'm misunderstanding, but I have two questions: what is the difference between the HCP_tracts_1 and HCP_tracts_5 directories? Secondly, are these atlases are averaged across subjects? Have you also made the atlases for individual HCP subjects publicly available? 

Thank you very much,
Brian

**Comment by swarrington1** [comment]
Hi Brian,
Thanks for your interest. 
The number refers to the threshold used to create the atlases, either 0.1% or 0.5% threshold applied to the individual tract maps prior to binarising and averaging across the cohort.

As hinted to, these are the cohort-averaged maps. We don't have plans to make the subject-wise tract maps available as this would be quite large. You can produce them using XTRACT however.

**Comment by bwinsto2** [comment]
Great--we will run XTRACT on individual subjects then. Thanks for the quick reply--have a wonderful holiday.
